name: Clang-format check
on: [pull_request]

jobs:
  style-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: DoozyX/clang-format-lint-action@v0.17
      continue-on-error: true
      with:
        source: '.'
        exclude: './third_party ./*/thirdparty'
        clangFormatVersion: 17
        inplace: True
        style: file

    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        message: '🤖 Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
