name: Clang-format check
on: [pull_request]

jobs:
  style-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./*/thirdparty'
        clangFormatVersion: 17
        inplace: True
        style: file

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: '🤖 Committing clang-format changes'
