name: Clang-format check
on: [pull_request]

jobs:
  style-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party'
        extensions: 'hpp,h,cpp,c'
        clangFormatVersion: 17
        style: file
