name: Clang-format check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install clang-format
        run : |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-18 main"
          sudo apt-get update
          sudo apt-get install -y clang-format-18
        
      - name: check-diff
        run : |
          diff=`git-clang-format --diff HEAD^`
          if ! [[ "$diff" = "no modified files to format" || "$diff" = "clang-format did not modify any files" ]]; then
              echo "The diff you sent is not formatted correctly."
              echo "The suggested format is"
              echo "$diff"
              exit 1
          fi
