name: Codestyle checker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './thirdparty'
        extensions: 'hpp,cpp'
        clangFormatVersion: 17
        style: 'file'
