name: Clang-format check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.9
      with:
        source: '.'
        exclude: './third_party'
        extensions: 'hpp,h,cpp,c'
        clangFormatVersion: 17.0.4
        style: file
