name: Clang-format check
on: [pull_request]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '18'
          check-path: 'engine'
  
      - name: Print clang-format version
        run: |
          clang-format-18 --version
        
      - name: check-diff
        run : |
          diff=$(git-clang-format --diff HEAD^)
          if ! [[ "$diff" = "no modified files to format" || "$diff" = "clang-format did not modify any files" ]]; then
              echo "The diff you sent is not formatted correctly."
              echo "The suggested format is"
              echo "$diff"
              exit 1
          fi
