name: Clang-format check
on: [pull_request]
permissions:
  contents: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  style-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Format all files
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./*/thirdparty'
        clangFormatVersion: 17
        inplace: True
        style: file

    - name: Commit changes
      run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git commit -am "🤖 Committing clang-format changes"
          git push
