name: Clang-format check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: install clang-format
      #   run : |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x llvm.sh
      #     sudo ./llvm.sh 18

      - name: Install Homebrew
        run: |
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
        
      - name: Install clang-format
        run: |
          brew install clang-format@18
  
      - name: Print clang-format version
        run: |
          clang-format --version
        
      - name: check-diff
        run : |
          diff=$(git-clang-format --diff HEAD^)
          if ! [[ "$diff" = "no modified files to format" || "$diff" = "clang-format did not modify any files" ]]; then
              echo "The diff you sent is not formatted correctly."
              echo "The suggested format is"
              echo "$diff"
              exit 1
          fi
