name: Clang-format check
on: [push]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - check: 'engine'
            exclude: '(thirdparty)'
    
    steps:
    - uses: actions/checkout@v3
    - uses: jidicula/clang-format-action@v4.11.0
      with:
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        clang-format-version: 18
