name: Clang-format check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install clang-format
        run : |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y clang-format-18 python3
          git clone https://github.com/llvm/llvm-project.git
          sudo ln -s $PWD/llvm-project/clang/tools/clang-format/git-clang-format /usr/bin/git-clang-format
        
      - name: check-diff
        run : |
          diff=$(git-clang-format --diff HEAD^)
          if ! [[ "$diff" = "no modified files to format" || "$diff" = "clang-format did not modify any files" ]]; then
              echo "The diff you sent is not formatted correctly."
              echo "The suggested format is"
              echo "$diff"
              exit 1
          fi
