name: Windows CI
on: [pull_request]
env:
  SOLUTION: Lumina.sln

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v3

    - name: Setup Premake
      uses: premake/setup-premake@v1
      with:
        version: 5.0.0-alpha16

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Generate project with tests
      run: premake5 --file=lumina.build.lua vs2022

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.build-configuration}} /p:Platform=x64 ${{env.SOLUTION}}
